%%1.5
%a
x = linspace(0,2*pi,20)';
[X,Y] = meshgrid(x,x);
%b
g = cos(X).*sin(Y);

%c
xc = linspace(0,2*pi,80)';

[Xc,Yc] = meshgrid(xc,xc);
%d
f = polyharm(Xc,Yc,X(:),Y(:),g(:));

surf(Xc,Yc,f)
xlabel('X')
ylabel('Y')
zlabel('f=Cos(x)*sin(y)')
title('Polyharm interpolant of a function')
g=cos(Xc).*sin(Yc);
diff = abs(f-g);
figure
contour(Xc,Yc,diff)
xlabel('X')
ylabel('Y')
title('Contour of the error generated by polyharm.m');
d = colorbar;
ylabel(d,'Error generated')