fun = @(x) (1+0.5*sin(1))/sinh(1) *sinh(x) - 0.5*sin(x);
func =@(x) -sin(x);


%%Iterate solutions to Heat PDE
[u,x,rnorm] = solveheat(1,func,1,0,1,20,1e-3,100);
[u2,~,~] = solveheat(1,func,1,0,1,20,1e-6,1000);
plot(x,fun(x),'r.',x,u,'b--',x,u2,'g:')
title("Solutions to the heat PDE")
legend("True solution","Approximated solution using solveheat.m","Solution with higher tolerance variable")
xlabel("x");
ylabel("Solution of the heat PDE");

%%Error generated
figure
diff = abs(fun(x)-u);
diff2 = abs(fun(x)-u2);
plot(x,diff,'r',x,diff2);
title("Error generated by approximating heat PDE")
legend("tol = 1e-3, 100 maxits","tol = 1e-6, 1000 maxits")
xlabel("x");
ylabel("Absolute value of error generated");

%2.6
N=100;
L=1;
alpha = 1;
u0 = 0;
uL = 1;
f = @(x) 80* exp(-(x-0.4).^2/0.001);
tol = 1e-3;
maxits = 10000;
[u3,x,rnorm] = solveheat(alpha,f,L,u0,uL,N,tol,maxits);
figure
plot(x,u3,'r-');
title("Solved Heat PDE")
legend("Heated by a candle")
xlabel("x");
ylabel("Solution of the heat PDE");